version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis
    ports:
      - 6379:6379

  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=project_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django_app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - type: 'bind'
        source: './backend'
        target: '/app'
    depends_on:
      - db
      - redis

  migrations:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python manage.py migrate
    volumes:
      - type: 'bind'
        source: './backend'
        target: '/app'
    depends_on:
      - db
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: celery -A config worker -l info
    volumes:
      - type: 'bind'
        source: './backend'
        target: '/app'
    depends_on:
      - db
      - redis
      - migrations

  celery_beat:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: celery -A config beat -l info
    volumes:
      - type: 'bind'
        source: './backend'
        target: '/app'
    depends_on:
      - db
      - redis
      - migrations
